// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dR5IfTArdHpenANzBpLkC26IEJxzIW0',
    appId: '1:408749924837:web:a04a3e448f8d5ccfef8f0c',
    messagingSenderId: '408749924837',
    projectId: 'blackout-3378f',
    authDomain: 'blackout-3378f.firebaseapp.com',
    storageBucket: 'blackout-3378f.firebasestorage.app',
    measurementId: 'G-0SDN3GDVVJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW3LchpUUHjNR9hvYGgy1wxKnEKQKPLqc',
    appId: '1:408749924837:android:3505d9cde24711eaef8f0c',
    messagingSenderId: '408749924837',
    projectId: 'blackout-3378f',
    storageBucket: 'blackout-3378f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6MZs_vsQUGi9QuSRFD2YwZQo6OWoo44s',
    appId: '1:408749924837:ios:7ea7c58bbf70a733ef8f0c',
    messagingSenderId: '408749924837',
    projectId: 'blackout-3378f',
    storageBucket: 'blackout-3378f.firebasestorage.app',
    iosBundleId: 'com.example.blackout',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6MZs_vsQUGi9QuSRFD2YwZQo6OWoo44s',
    appId: '1:408749924837:ios:7ea7c58bbf70a733ef8f0c',
    messagingSenderId: '408749924837',
    projectId: 'blackout-3378f',
    storageBucket: 'blackout-3378f.firebasestorage.app',
    iosBundleId: 'com.example.blackout',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5dR5IfTArdHpenANzBpLkC26IEJxzIW0',
    appId: '1:408749924837:web:e7255f6898c06cc4ef8f0c',
    messagingSenderId: '408749924837',
    projectId: 'blackout-3378f',
    authDomain: 'blackout-3378f.firebaseapp.com',
    storageBucket: 'blackout-3378f.firebasestorage.app',
    measurementId: 'G-R6RH6L38XL',
  );
}
